name: Generate Releases

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  update:
    name: Generate Releases
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: ./update.sh
        env:
            KEY: ${{ secrets.KEY }}
      - name: Commit and push changes back to PR
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add .
            git commit -m "chore: auto-fix from pre-merge script" || echo "No changes to commit"
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}